server:
  port: 8082
spring:
  application:
    name: user-service
  sql:
    init:
      mode: always
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/postgres
    username: postgres
    password: example
  cloud:
    function:
      definition: flagPersonTransactionQueueListener;
    stream:
      bindings:
        flagPersonTransactionQueueListener-in-0:
          destination: flagpersontransactionexchange
          group: flagpersontransactionqueue
      rabbit:
        bindings:
          flagPersonTransactionQueueListener-in-0:
            consumer:
              queueNameGroupOnly: true
              binding-routing-key-delimiter: ","
              bindingRoutingKey: "flagpersonransactionroutingkey"
              exchangeType: direct
              autoBindDlq: false

logging:
  level:
    org:
      springframework:
        r2dbc: DEBUG
person:
  event:
    save:
      queue: savepersonqueue
      exchange: savepersonexchange
      routingKey: savepersonroutingkey
    update:
      queue: updatepersonqueue
      exchange: updatepersonexchange
      routingkey: updatepersonroutingkey
    delete:
      queue: deletepersonqueue
      exchange: deletepersonexchange
      routingkey: deletepersonroutingkey
    flag:
      queue: flagpersonqueue
      exchange: flagpersonexchange
      routingkey: flagpersonroutingkey