server:
  port: 8082
spring:
  application:
    name: user-service
  sql:
    init:
      mode: always
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/postgres
    username: postgres
    password: example
logging:
  level:
    org:
      springframework:
        r2dbc: DEBUG